SEED: 0
MODEL:
  BINARY_CLASSIFICATION: True
  OUT_CHANNELS: 2
  IN_CHANNELS: 3
  LOSS_TYPE: 'CrossEntropyLoss'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  LEGACY: False # If True, use the fixed UNet for backwards compatibility
  TOPOGRAPHY: [64, 128, 256, 512,]
  SIMPLE_INTERPOLATION: False # True: Bilinear interpo, False: Deconv interpo

DATASETS:
  TRAIN: ("/local_storage/datasets/xview2/full/train/",)
  TEST: ("/local_storage/datasets/xview2/full/test/",)
  INFERENCE: ("/local_storage/datasets/xview2/full/real_test_set/",)
OUTPUT_BASE_DIR: ('/local_storage/users/pshi/logs/unet/')
TRAINER:
  LR: 0.001
  BATCH_SIZE: 1
  EPOCHS: 1000
DATALOADER:
  NUM_WORKER: 1
  SHUFFLE: True
AUGMENTATION:
  # Random cropping of the images
  RESIZE: False # target image size (before cropping)
  RESIZE_RATIO: 1.0
  CROP: False
  CROP_SIZE: 1024


