SEED: 1339 # best seed so far 1339 or 43
MODEL:
  BINARY_CLASSIFICATION: False
  OUT_CHANNELS: 3
  IN_CHANNELS: 3
  LOSS_TYPE: 'CrossEntropyLoss'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  EDGE_WEIGHT: 1 # CHANGE ME
  LEGACY: False # If True, use the fixed UNet for backwards compatibility
  TOPOLOGY: [64, 128, 256, 512,]
  BLOCK_TYPE: 'Triple'
  SIMPLE_INTERPOLATION: False # True: Bilinear interpo, False: Deconv interpo
  USE_ATTENTION: False
  MULTISCALE_CONTEXT: # For U-Net bottleneck context module
    ENABLED: False
    TYPE: 'Simple' # [Simple, PyramidSum, ParallelSum]
    DILATION: []
  BACKBONE:
    ENABLED: False
    TYPE: 'resnet34'
THRESH: 0.52
DATASETS:
  TRAIN: ("/local_storage/datasets/xview2/full_new/train/",)
  TEST: ("/local_storage/datasets/xview2/full_new/test/",)
  INFERENCE: ("/local_storage/datasets/xview2/full_new/real_test_set/",)
  PRE_OR_POST: 'pre' # 'pre' vs 'post' disaster images to use
  USE_CLAHE_VARI: False
OUTPUT_BASE_DIR: ('/Midgard/home/pshi/run_logs/unet/')
TRAINER:
  LR: 0.0001
  BATCH_SIZE: 1
  EPOCHS: 1000
  EDGE_LOSS_SCALE: 1
DATALOADER:
  NUM_WORKER: 1
  SHUFFLE: True
  LEGACY_MASK_RASTERIZATION: False

AUGMENTATION:
  # Random cropping of the images
  RESIZE: False # target image size (before cropping)
  RESIZE_RATIO: 1.0
  CROP_TYPE: 'importance'
  CROP_SIZE: 256
  IMAGE_OVERSAMPLING_TYPE: 'simple'
  ENABLE_VARI: False # False NDVI for detecting vegetation
  RANDOM_FLIP_ROTATE: False
  KERNEL_SIZE: 5 # the bigger the thicker the edges, odd values preferred
  MASK_METHOD: 'dilation' # either 'erosion' or 'dilation'